### PR TITLE
Update module.json

### PR DESCRIPTION
**Pull request by Mystery-Man-From-Ouperspace**
Added French translations.

### CODE REVIEW

**Comment by Mystery-Man-From-Ouperspace** [comment]
File for French translations is here : [https://github.com/Mystery-Man-From-Ouperspace/foundryvtt-forien-easy-polls/blob/master/dist/languages/fr.json](https://github.com/Mystery-Man-From-Ouperspace/foundryvtt-forien-easy-polls/blob/master/dist/languages/fr.json)

**Comment by Forien** [comment]
> File for French translations is here : https://github.com/Mystery-Man-From-Ouperspace/foundryvtt-forien-easy-polls/blob/master/dist/languages/fr.json

Could you please include the file in the Pull Request?

**Comment by Mystery-Man-From-Ouperspace** [comment]
Sorry, I can't : I have no right to create a file in your own version ; please create an empty fr.json file, so I could update it!

**Comment by Forien** [comment]
> Sorry, I can't : I have no right to create a file in your own version ; please create an empty fr.json file, so I could update it!

You don't create files in my repository, you perform all changes on your forked repository and then open a new Pull Request from your repository to my repository

**Review by Forien — APPROVED** [review]

**Pull request merged**
